[package]
name = "mylib"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
winit = { version = "0.30"}
env_logger = "0.10"
log = "0.4"
wgpu = "28.0"
pollster = "0.3"
bytemuck = { version = "1.13", features = ["derive"] }
glam = { version = "0.32.0", features = ["bytemuck"] }
